File Name: 018_HW_WrangleAutomation.ipynb

1. write a function to convert the data file from wide to tidy long format. assume input data consist of 4 columns, handle any number of rows

In [8]:
import pandas as pd
import numpy as np

In [9]:
display(myData)

,Condition_A_Level_1,Condition_A_Level_2,Condition_B_Level_1,Condition_B_Level_2
0,10,20,30,40
1,15,25,35,45

In [16]:
def automation_wrangling(filename, var1 = ['Condition_A', 'Condition_B'], var2 = ['level_1', 'level_2']) :
    import pandas as pd
    import numpy as np
    myFile = pd.read_csv(filename)
    
    # convert to numpy array
    myData = myFile.to_numpy()
    
    # get the numbers of rows and columns 
    obs, grp = myData.shape
    
    new_length = obs * grp
    
    values_col = np.reshape(myData, (new_length, 1), order = "F")
    
    values_col = np.squeeze(values_col)
    
    # constructing the outer grouping variable
    condition = pd.Series(var1)
    condition = condition.repeat(obs * 2)
    condition = condition.reset_index(drop = True)
    
    # constructing the innner grouping variable
    level = pd.Series(var2)
    level = level.repeat(obs)
    level = pd.concat([level] * 2, ignore_index = True)
    
    # constructing the data frame
    dataFrame = pd.DataFrame(
        {
        "Data" : values_col, 
        "Condition" : condition,
        "Level" : level
        }
    )
    
    return dataFrame

convert from wide to tidy long format

In [17]:
filename = "~/Desktop/MyGitRepos/sc62286_FDS1/datasets/018_HW_2x2_data.csv"

automation_wrangling(filename)

   Data    Condition    Level
0    10  Condition_A  level_1
1    15  Condition_A  level_1
2    20  Condition_A  level_2
3    25  Condition_A  level_2
4    30  Condition_B  level_1
5    35  Condition_B  level_1
6    40  Condition_B  level_2
7    45  Condition_B  level_2

2. Test my function on the next file

In [18]:
import pandas as pd
import numpy as np

filename = "~/Desktop/MyGitRepos/sc62286_FDS1/datasets/018_HW_2x2_data2.csv"

automation_wrangling(filename)

    Data    Condition    Level
0     10  Condition_A  level_1
1     15  Condition_A  level_1
2     20  Condition_A  level_1
3     25  Condition_A  level_1
4     30  Condition_A  level_1
5     35  Condition_A  level_1
6     20  Condition_A  level_2
7     25  Condition_A  level_2
8     30  Condition_A  level_2
9     35  Condition_A  level_2
10    40  Condition_A  level_2
11    45  Condition_A  level_2
12    30  Condition_B  level_1
13    35  Condition_B  level_1
14    40  Condition_B  level_1
15    45  Condition_B  level_1
16    50  Condition_B  level_1
17    55  Condition_B  level_1
18    40  Condition_B  level_2
19    45  Condition_B  level_2
20    50  Condition_B  level_2
21    55  Condition_B  level_2
22    60  Condition_B  level_2
23    65  Condition_B  level_2